services:
  db:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:devpass@db:5432/postgres

volumes:
  postgres_data: